#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import os
import sys
import gzip
import json
import wget

def main(work_dir):
    change_work_dir(work_dir)
    for line in sys.stdin:
        url = line.strip()
        gzfile = download(url)
        for event in gzcontent(gzfile):
            user, repo = parse_starred(event)
            if user and repo:
                print('%s\t%s' % (user, repo))

def change_work_dir(target):
    if not os.path.exists(target):
        os.makedirs(target)
    if not os.path.isdir(target):
        print("'./%s' should be a directory" % target, file=sys.stderr)
        exit(1)
    os.chdir(target)

def download(url):
    expecting_filename = url.rsplit('/', 1)[-1]
    if os.path.exists(expecting_filename):
        return expecting_filename
    else:
        return wget.download(url, bar=None)

def gzcontent(gzfile):
    try:
        with gzip.open(gzfile, 'rb') as f:
            for line in f:
                yield line
    except IOError:
        print("FAILED: '%s' is invalid. delete it" % gzfile, file=sys.stderr)
        os.remove(gzfile)

def parse_starred(event):
    """See: https://developer.github.com/v3/activity/events/types/#watchevent"""
    ev = json.loads(event)
    if ev['type'] == 'WatchEvent':
        return ev['actor']['login'], ev['repo']['name']
    else:
        return None, None

if __name__ == '__main__':
    main('downloads')
