#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import os
import sys
import gzip
import wget

def main(work_dir):
    change_work_dir(work_dir)
    for line in sys.stdin:
        url = line.strip()
        gzfile = download(url)
        print(gzcontent(gzfile))

def change_work_dir(target):
    if not os.path.exists(target):
        os.makedirs(target)
    if not os.path.isdir(target):
        print("'./%s' should be a directory" % target, file=sys.stderr)
        exit(1)
    os.chdir(target)

def download(url):
    return wget.download(url, bar=None)

def gzcontent(gzfile):
    with gzip.open(gzfile, 'rb') as f:
        return f.read()

if __name__ == '__main__':
    main('downloads')
