#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import sys
import re
import predictionio

def main(file_name):
    exporter = predictionio.FileExporter(file_name=file_name)
    count = 0
    for line in sys.stdin:
        user, repo = line.strip().split('\t')
        if user and repo:
            new_event(exporter, user, repo)
            count += 1
            print("'{user}' - '{repo}'".format(user=user, repo=repo))
        else:
            print('FAILED: %s' % line, file=sys.stderr)
    exporter.close()
    print('count: %d' % count)
        
def new_event(exporter, user_id, item_id):
    exporter.create_event(
        event="star",
        entity_type="user",
        entity_id=user_id,
        target_entity_type="item",
        target_entity_id=item_id)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('usage: %s <outfile>' % __file__, file=sys.stderr)
        exit(1)

    file_name = sys.argv[1]
    main(file_name)
