#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import sys
from datetime import datetime, timedelta

COMMAND='http://data.githubarchive.org/{date}-{hour}.json.gz'

def urls_for_last(begin, end):
    _1day = timedelta(days=1)
    d = begin
    while d != end:
        for line in urls_for_date(d):
            print(line)
        d += _1day

def urls_for_date(date):
    str_date = date.strftime('%Y-%m-%d')
    for i in xrange(0, 24):
        str_hour = int(i)
        yield COMMAND.format(date=str_date, hour=str_hour)

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('usage: %s <begin> <end>' % __file__, file=sys.stderr)
        print("<begin>, <end>: formatted in 'YYYY-MM-DD'", file=sys.stderr)
        exit(1)
    begin  = datetime.strptime(sys.argv[1], '%Y-%m-%d').date()
    end  = datetime.strptime(sys.argv[2], '%Y-%m-%d').date()
    urls_for_last(begin, end)
