#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import sys
from datetime import datetime, timedelta
import pytz

COMMAND='http://data.githubarchive.org/{date}-{hour}.json.gz'

def urls_for_last(days):
    today = datetime.now(pytz.utc).date()
    _1day = timedelta(days=1)

    d = today - timedelta(days=days)
    while d != today:
        d += _1day
        for line in urls_for_date(d):
            print(line)

def urls_for_date(date):
    str_date = date.strftime('%Y-%m-%d')
    for i in xrange(0, 24):
        str_hour = int(i)
        yield COMMAND.format(date=str_date, hour=str_hour)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('usage: %s <days>' % __file__, file=sys.stderr)
        exit(1)
    days = int(sys.argv[1])
    urls_for_last(days)
